# Generated by Django 3.0.1 on 2020-01-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_person_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='Persons',
        ),
    ]
