# Generated by Django 3.0.1 on 2020-01-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200130_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='p_id',
            new_name='post',
        ),
    ]
