# Generated by Django 3.0.1 on 2020-01-30 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200130_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='post_id',
        ),
    ]
