# Generated by Django 3.0.3 on 2020-02-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Userlogin',
        ),
    ]
