# Generated by Django 3.0.3 on 2020-02-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200204_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usersignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('Contactno', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
