# Generated by Django 3.0.3 on 2020-02-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='userid',
            new_name='username',
        ),
    ]
